zh: |
  <!-- Reply in zh -->

thinking: |
  <!-- Please think step-by-step -->

thinking_xml: |
  <!-- Think within <thinking> before output -->

code: |
    ```
    
    ```

xml: |
    <>
    
    </>
